### ISSUE TITLE
Compilation errors with Rust E57 library and wasm-bindgen

### ISSUE THREAD

**Issue by Codechefkhush** [cry-inc/e57#2]
Hi,
 I've been using the Rust E57 library in one of my assignments, and I must say it's a great tool. I appreciate the effort you put into creating a pure Rust solution without any unsafe code. However, I've encountered an issue while trying to compile the Rust code to WebAssembly using  #[wasm_bindgen] tool. It seems to be related to the integration of the E57 library with the WebAssembly target. I've followed the necessary steps and have encountered the following errors:

1) error: #[wasm_bindgen] generic impls aren't supported
  --> src\e57_reader.rs:48:5
   |
48 | impl<T: Read + Seek> E57Reader<T> {
   |     ^^^^^^^^^^^^^^^^

2) error: paths with type parameters are not supported yet
   --> src\e57_reader.rs:268:6
    |
268 | impl E57Reader<BufReader<File>> {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^

These errors suggest that there are limitations or compatibility issues with using generic implementations and type parameterized paths in the context of #[wasm_bindgen]. I believe this issue is specific to the integration of the E57 library with  #[wasm_bindgen]. I've successfully compiled other Rust projects to WebAssembly using #[wasm_bindgen], so I suspect there might be some specific considerations or configurations required for this library. I'm eager to use the Rust E57 library in my WebAssembly project, and resolving this issue would be of great help.

**Comment by cry-inc** [comment]
Can you please post your Rust code that uses wasm_bindgen and the E57 library? I was unable to reproduce your issue. This is my test code that compiled and worked without any hickups:

```
use e57::E57Reader;
use std::io::Cursor;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn test_xml_extract(input: &[u8]) -> String {
    let reader = Cursor::new(input);
    let e57 = E57Reader::new(reader).unwrap();
    let xml = e57.xml();
    xml.to_string()
}
```

Its probably to be expected that wasm_bindgen cannot magically translate generic Rust arguments. You probably either have to copy the contents of the file that should be parsed over into the WASM memory. Or setup some more involved code that can stream the data from the JS context to the WASM context.

**Comment by Codechefkhush** [comment]
Yes sure, thank you for your response. 
**Here's my rust code which uses wasm_bindgen and the E57 library -**

`use e57::E57Reader;
use std::fs::File;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn parse_e57_file(file_path: &str) {
    let reader = E57Reader::from_file(file_path).unwrap();
}`

**Here's detail error -** 

`Uncaught (in promise) RuntimeError: unreachable
    at __rust_start_panic (2397f9de451fc3a18581.module.wasm:0xc06c6)
    at rust_panic (2397f9de451fc3a18581.module.wasm:0xbf5bc)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (2397f9de451fc3a18581.module.wasm:0xa51d4)
    at std::panicking::begin_panic_handler::{{closure}}::hfa40135feb109919 (2397f9de451fc3a18581.module.wasm:0xac74e)
    at std::sys_common::backtrace::__rust_end_short_backtrace::haf21bfec9a028e09 (2397f9de451fc3a18581.module.wasm:0xc05f7)
    at rust_begin_unwind (2397f9de451fc3a18581.module.wasm:0xb8de2)
    at core::panicking::panic_fmt::he4489d678d6570d5 (2397f9de451fc3a18581.module.wasm:0xbdd5f)
    at core::result::unwrap_failed::h9c69c0d7a98df92b (2397f9de451fc3a18581.module.wasm:0xae18a)
    at core::result::Result<T,E>::unwrap::h5d965d21a18d8152 (2397f9de451fc3a18581.module.wasm:0x9a90b)
    at missionrust::parse_e57_file::h8d553b808c8ba1a4 (2397f9de451fc3a18581.module.wasm:0xaf97f)`

**Comment by cry-inc** [comment]
To get more helpful errors you should look into the crate https://crates.io/crates/console_error_panic_hook. It will provide the original Rust errors which will give you a better hint about whats going on. In your example that would be something like this:

    panicked at 'called `Result::unwrap()` on an `Err` value: Read { desc: "Unable to open file", source: Some(Error { kind: Unsupported, message: "operation not supported on this platform" }) }

When you execute your WASM code inside a browser that means it runs in a sandbox. This sandbox has no access to your computers file system, meaning whatever file path you supply cannot be read. This is why it says not supported on this platform. Instead you need another way to get the E57 file data into you WASM sandbox. If the files are small enough the easiest option is to read them into the shared memory of the WASM sandbox and access it from there. See example code below.

If your files are very big, you are out of luck and need to find a way to stream them into your sandbox. However, this is not something that will be solved by this E57 library, since this is a generic Rust/WASM problem about file IO.

**Rust Code**
```
use e57::{E57Reader, Point};
use std::io::Cursor;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn point_average(input: &[u8]) -> Vec<f64> {
    console_error_panic_hook::set_once();
    let reader = Cursor::new(input);
    let mut e57 = E57Reader::new(reader).unwrap();
    let point_clouds = e57.pointclouds();
    let point_cloud = point_clouds.first().unwrap();
    let iter = e57.pointcloud(point_cloud).unwrap();
    let mut result = vec![0.0, 0.0, 0.0];
    for i in iter {
        let values = i.unwrap();
        let point = Point::from_values(values, &point_cloud.prototype).unwrap();
        let coords = point.cartesian.unwrap();
        result[0] += coords.x / point_cloud.records as f64;
        result[1] += coords.y / point_cloud.records as f64;
        result[2] += coords.z / point_cloud.records as f64;
    }
    result
}
```

**HTML + JavaScript**
```
<!DOCTYPE html>
<html>
<body>
    <input type="file" id="file_picker"></input><br>
    <pre id="output"></pre>
    <script type="module">
        import init, { point_average } from "./pkg/wasm_e57.js"; // generated with "wasm-pack build -t web"
        await init();
        document.getElementById("file_picker").addEventListener("change", async function () {
            let file = this.files[0];
            const data = await file.arrayBuffer();
            let view = new Uint8Array(data);
            let result = point_average(view);
            document.getElementById("output").innerHTML = result;
        });
    </script>
</body>
</html>
```
